### ISSUE TITLE
when trying to install kitools keep getting the error below

### ISSUE THREAD

**Issue by smouksassi** [ki-tools/kitools#4]
Error: Failed to install 'kitools' from GitHub:
  (converted from warning) unable to access index for repository https://sage-bionetworks.github.io/ran/bin/windows/contrib/3.6:
  cannot open URL 'https://sage-bionetworks.github.io/ran/bin/windows/contrib/3.6/PACKAGES'

**Comment by hafen** [comment]
There is a newer version of kitools.

See here:

https://github.com/ki-tools/kitools-r

and here:

https://ki-tools.github.io/kitools-r/

Sorry about that - I will archive this repository.
